---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(robustSL)
library(dplyr)
library(ggplot2)
library(tidyr)
```


## Example 1

```{r}
I <- 100
m <- 4
epsilon <- 0
theoretical_ratio <- sqrt(2)

true_M <- paste0("M", m)
cpt <- 0
for(i in 1:I){
  df <- simulate_blocs(500, 
                       M = m, 
                       ratio_card_max = theoretical_ratio,
                       epsilon = epsilon)
  cl_true <- df$cluster
  cl_estim <- df %>%
    select(x, y) %>%
    robust_hclust(M=2, Mmax = 10, method="single", M_init = 100) %>% 
    `[[`(true_M)
  if(check_clustering(cl_true, cl_estim)){
    cpt <- cpt + 1
  }
  cpt
}
cpt/I
```

## Example 2

```{r}
simulate_blocs(500, M=4, epsilon = 0.1) %>%
  select(x, y) %>%
  robust_hclust(M = 2, Mmax = 5, method = "single", M_init = 100) %>%
  gather(key = "M", value = "groups", -x, -y) %>% 
  ggplot() + aes(x, y) + facet_wrap(~M) + geom_point(aes(color=groups))
```

